site_name: AndroidTamer
site_description: Documentation for Android Tamer
site_author: AndroidTamer Team
docs_dir: ./
#site_dir: ../site/  
#theme: readthedocs
markdown_extensions:
  - markdown_newtab
  - oembed
  - markdown_checklist.extension
include_next_prev: false
copyright: (c) Android Tamer Team
site_favicon: favicon.ico
#theme_dir: theme